"""
Django settings for scandy project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os, environ

# set env files
env = environ.Env(
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# env 읽기
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# 구글 인증키(credentials.json)파일 설정.
GOOGLE_OAUTH_JSON = BASE_DIR / "security" / "credentials.json"

GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_PASSWORD = env("GOOGLE_CLIENT_PASSWORD")
OPENAI_API_KEY = env("OPENAI_API_KEY")


# JWT secret key 설정
JWT_SECRET_KEY = env("JWT_SECRET_KEY")
JWT_ALGORITHM = "HS256"
JWT_EXP_DELTA_SECONDS = 3600 # 1시간

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # external libs
    'rest_framework',
    'drf_spectacular',
    'corsheaders',

    # your apps here
    'apps.gpt',
    'apps.users',
    'apps.tasks',
    'apps.calendars',
    'apps.ocr',
    'apps.session_tokens',
    'apps.google_calendar',
]

REST_FRAMEWORK = {
    # YOUR SETTINGS  drf의 schema 클래스를 drf-specacular의 AutoSchema로 교체해줍니다.
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    
    'SERVE_INCLUDE_SCHEMA': False, # OAS3 Meta정보 API를 비노출 처리한다.
    
    'COMPONENT_SPLIT_REQUEST': True, # 웹 인터페이스에서 파일 업로드 기능 제공 설정

    # 헤더 관련
    'SECURITY': [{'token': []}],
    'COMPONENTS': {
        'securitySchemes': {
            'token': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'token',  # Authorization 대신 Access-Token 사용
                'description': (
                    "JWT Access Token 입력\n\n"
                    "예시: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...`"
                ),
            },
        },
    },

    # Swagger 문서 접근 권한
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],

    # 기본 cookieAuth, basicAuth 제거
    'APPEND_COMPONENTS': {
        'securitySchemes': {},
    },

    # 자동으로 추가되는 기본 auth 비활성화
    'APPEND_SECURITY': [],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'scandy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scandy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db' / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    'token',   # 프론트 커스텀 토큰 통과 위해 추가
]

CORS_ALLOWED_ORIGINS = [ #API 호출할 수 있는 출처 목록
  "http://127.0.0.1:8000",
  "https://127.0.0.1:8000",
  "http://localhost:5173",
  "http://localhost:5174",
  "https://sein0327.shop",
  "https://api.sein0327.shop",
  "https://www.sein0327.shop",
  "https://scandy.vercel.app",
]

CSRF_TRUSTED_ORIGINS = [ #CSRF 토큰 검증 통과
  "http://127.0.0.1:8000",
  "https://127.0.0.1:8000",
  "http://localhost:5173",
  "http://localhost:5174",
  "https://sein0327.shop",
  "https://api.sein0327.shop",
  "https://www.sein0327.shop",
  "https://scandy.vercel.app",
]

DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

if DEBUG:
    # --- 로컬 개발 환경 ---
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    COOKIE_SECURE = False  # (커스텀 쿠키 설정 시 참조용)
    COOKIE_SAMESITE = "Lax"
else:
    # --- 배포 환경 ---
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    COOKIE_SECURE = True
    COOKIE_SAMESITE = "None"

CORS_ALLOW_CREDENTIALS = True #HTTP 자격증명 추가
# CSRF_COOKIE_SECURE = True #http 보안!
# SESSION_COOKIE_SECURE = True #위와 동일

SESSION_COOKIE_AGE = 86400  # 초 단위: 24시간 = 86400초
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 브라우저를 닫아도 세션 유지

# SESSION_COOKIE_SAMESITE = 'None'
# CSRF_COOKIE_SAMESITE = 'None'

# 프록시 가져오기.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# FRONT_ORIGIN = env.str("FRONT_ORIGIN").rstrip("/")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CLOVA_OCR_URL = env("CLOVA_OCR_URL")
CLOVA_OCR_SECRET = env("CLOVA_OCR_SECRET")