# Generated by Django 5.2.5 on 2025-10-29 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('google_calendar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.IntegerField(default=0)),
                ('calendar', models.ForeignKey(db_column='calendar_id', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='calendars.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False, null=True)),
                ('repeat', models.CharField(blank=True, choices=[('NONE', '반복 없음'), ('DAILY', '매일'), ('WEEKLY', '매주'), ('MONTHLY', '매월'), ('YEARLY', '매년')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('calendar', models.ForeignKey(db_column='calendar_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='calendars.calendar')),
                ('tag', models.ForeignKey(blank=True, db_column='tag_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='calendars.tag')),
            ],
        ),
    ]
