# Generated by Django 5.2.7 on 2025-10-31 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_alter_calendar_user'),
        ('users', '0005_rename_google_sync_user_is_google_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='name',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='users.user'),
        ),
    ]
