# Generated by Django 5.2.7 on 2025-10-31 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_remove_calendar_is_primary_remove_calendar_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='google_calendar_id',
        ),
    ]
