# Generated by Django 5.2.7 on 2025-10-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_remove_calendar_google_calendar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='until',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='repeat',
            field=models.CharField(choices=[('NONE', '반복 없음'), ('DAILY', '매일'), ('WEEKLY', '매주'), ('MONTHLY', '매월'), ('YEARLY', '매년')], default='NONE', max_length=10),
        ),
    ]
