# Generated by Django 5.2.5 on 2025-11-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0005_schedule_until_alter_schedule_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='locate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
