# Generated by Django 5.2.7 on 2025-11-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0006_schedule_end_date_schedule_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_date',
        ),
    ]
