# Generated by Django 5.2.7 on 2025-11-02 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0007_remove_schedule_end_date_remove_schedule_start_date'),
        ('google_calendar', '0005_googlecalendar_unique_primary_calendar_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='google_calendar_id',
            field=models.ForeignKey(blank=True, db_column='google_calendar_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_calendars', to='google_calendar.googlecalendar'),
        ),
    ]
