# Generated by Django 5.2.7 on 2025-11-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0008_schedule_google_calendar_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='google_calendar_id',
            new_name='google_calendar',
        ),
    ]
