# Generated by Django 5.2.7 on 2025-11-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0009_rename_google_calendar_id_schedule_google_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
    ]
