# Generated by Django 5.2.7 on 2025-11-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0006_schedule_locate'),
        ('calendars', '0010_alter_schedule_all_day'),
    ]

    operations = [
    ]
