# Generated by Django 5.2.7 on 2025-11-11 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0011_merge_20251103_1903'),
        ('tasks', '0004_rename_task_image_image_image_remove_image_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tasks.task'),
        ),
    ]
