# Generated by Django 5.2.7 on 2025-11-11 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0012_schedule_task'),
        ('tasks', '0004_rename_task_image_image_image_remove_image_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='task',
            field=models.ForeignKey(blank=True, db_column='task_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tasks.task'),
        ),
    ]
