# HTTP → HTTPS 리다이렉트
server {
    if ($host = sein0327.shop) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name sein0327.shop www.sein0327.shop scandy.vercel.app;
    # ex) server_name  mingi0130.shop  www.mingi0130.shop;
    return 301 https://$host$request_uri;
}

# HTTPS 서버 블록
server {
    listen 443 ssl http2;
    server_name sein0327.shop www.sein0327.shop scandy.vercel.app;
    client_max_body_size 20M;
    # ex) server_name  mingi0130.shop  www.mingi0130.shop;

    # SSL 설정 (Let’s Encrypt 기본 경로)
    # !! 구매한 도메인에는 본인 도메인이 들어가야 함
    # etc/letsencrypt -> security/로 마운트
    ssl_certificate /security/live/sein0327.shop/fullchain.pem; # managed by Certbot
    ssl_certificate_key /security/live/sein0327.shop/privkey.pem; # managed by Certbot
    include             /security/options-ssl-nginx.conf;
    ssl_dhparam         /security/ssl-dhparams.pem;

    # media 제공.
    location /media/ {
        alias /media/;
    }

    # 정적 파일 제공
    location /static/ {
        alias /static/;
        expires 30d;
        add_header Cache-Control "public";
    }

    # Django/Gunicorn 프록시
    location / {
        proxy_pass         http://scandy:8000;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
    }

}