# Generated by Django 5.2.7 on 2025-11-01 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('google_calendar_str_id', models.CharField(max_length=255)),
                ('is_activated', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='google_calendars', to='users.user')),
            ],
        ),
    ]
