# Generated by Django 5.2.7 on 2025-11-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0002_googlecalendar_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendar',
            name='google_calendar_str_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
