# Generated by Django 5.2.7 on 2025-11-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0003_alter_googlecalendar_google_calendar_str_id'),
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendar',
            name='google_calendar_str_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='googlecalendar',
            unique_together={('user', 'google_calendar_str_id')},
        ),
    ]
