# Generated by Django 5.2.7 on 2025-11-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0004_alter_googlecalendar_google_calendar_str_id_and_more'),
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='googlecalendar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='unique_primary_calendar_per_user'),
        ),
    ]
