# Generated by Django 5.2.5 on 2025-10-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('google_sync', models.BooleanField(default=False)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
