# Generated by Django 5.2.7 on 2025-10-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('google_sync', models.BooleanField(default=False)),
                ('google_sub', models.CharField(blank=True, max_length=255, null=True)),
                ('google_refresh_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
