# Generated by Django 5.2.7 on 2025-10-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_alter_calendar_user'),
        ('users', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
