# Generated by Django 5.2.5 on 2025-10-29 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ocr_result', models.TextField(blank=True, null=True)),
                ('llm_result', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
                ('schedule', models.ForeignKey(db_column='calendar_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='calendars.schedule')),
            ],
        ),
    ]
