# Generated by Django 5.2.7 on 2025-10-29 04:29

import apps.tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='task_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tasks.models.image_upload_path),
        ),
    ]
