# Generated by Django 5.2.5 on 2025-11-03 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0006_schedule_locate'),
        ('tasks', '0002_image_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='image',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='calendars.schedule'),
        ),
    ]
