# Generated by Django 5.2.7 on 2025-11-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_image_task_alter_image_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='task_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='schedule',
        ),
    ]
